### ISSUE TITLE
Unable to train model in Python

### ISSUE THREAD

**Issue by ronaldtse** [interscript/rababa#18]
I've been trying to run Rababa to train models but have been unable to due to this error:

```
Traceback (most recent call last):
  File "/home/runner/work/rababa-models/rababa-models/rababa/python/train.py", line 8, in <module>
    from trainer import (
  File "/home/runner/work/rababa-models/rababa-models/rababa/python/trainer.py", line 15, in <module>
    from diacritizer import CBHGDiacritizer
ImportError: cannot import name 'CBHGDiacritizer' from 'diacritizer' (/home/runner/work/rababa-models/rababa-models/rababa/python/diacritizer.py)
```

The `CBHGDiacritizer` code no longer exists in Rababa.

I've uploaded the workflow attempted to train here:
https://github.com/secryst/rababa-models/blob/main/.github/workflows/train.yml

The full logs can be seen here:
https://github.com/secryst/rababa-models/runs/3218393663?check_suite_focus=true

**Comment by ronaldtse** [comment]
Problem fixed by @gilgameshjw . GHA training tests implemented now.
